### ISSUE TITLE
The pod resource is not created in the workload cluster

### ISSUE THREAD

**Issue by XinRedhat** [openshift-pipelines/pipelines-service#78] opened 2022-05-25 07:28 UTC
Deploy  a kcp environment running in a container by using kcp's official image(ghcr.io/kcp-dev/kcp:release-0.4). When the workloadcluster and Syncer are created. The pod resource is not created in the workload cluster. 

```
$ KUBECONFIG=kcp_kubeconfig  kubectl kcp ws current                                                     1 
Current workspace is "root:default:demo".

$ KUBECONFIG=kcp_kubeconfig kubectl api-resources
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
configmaps                        cm           v1                                     true         ConfigMap
events                            ev           v1                                     true         Event
limitranges                       limits       v1                                     true         LimitRange
namespaces                        ns           v1                                     false        Namespace
resourcequotas                    quota        v1                                     true         ResourceQuota
secrets                                        v1                                     true         Secret
serviceaccounts                   sa           v1                                     true         ServiceAccount
mutatingwebhookconfigurations                  admissionregistration.k8s.io/v1        false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io/v1        false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io/v1                false        CustomResourceDefinition
apiresourceimports                             apiresource.kcp.dev/v1alpha1           false        APIResourceImport
negotiatedapiresources                         apiresource.kcp.dev/v1alpha1           false        NegotiatedAPIResource
apibindings                                    apis.kcp.dev/v1alpha1                  false        APIBinding
apiexports                                     apis.kcp.dev/v1alpha1                  false        APIExport
apiresourceschemas                             apis.kcp.dev/v1alpha1                  false        APIResourceSchema
deployments                       deploy       apps/v1                                true         Deployment
tokenreviews                                   authentication.k8s.io/v1               false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io/v1                true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io/v1                false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io/v1                false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io/v1                false        SubjectAccessReview
certificatesigningrequests        csr          certificates.k8s.io/v1                 false        CertificateSigningRequest
leases                                         coordination.k8s.io/v1                 true         Lease
events                            ev           events.k8s.io/v1                       true         Event
flowschemas                                    flowcontrol.apiserver.k8s.io/v1beta1   false        FlowSchema
prioritylevelconfigurations                    flowcontrol.apiserver.k8s.io/v1beta1   false        PriorityLevelConfiguration
clusterrolebindings                            rbac.authorization.k8s.io/v1           false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io/v1           false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io/v1           true         RoleBinding
roles                                          rbac.authorization.k8s.io/v1           true         Role
conditions                                     tekton.dev/v1alpha1                    true         Condition
pipelineresources                              tekton.dev/v1alpha1                    true         PipelineResource
pipelineruns                      pr,prs       tekton.dev/v1beta1                     true         PipelineRun
runs                                           tekton.dev/v1alpha1                    true         Run
taskruns                          tr,trs       tekton.dev/v1beta1                     true         TaskRun
workloadclusters                               workload.kcp.dev/v1alpha1              false        WorkloadCluster
```

**Comment by bnallapeta** [comment] 2022-05-25 07:34
@XinRedhat in your description, do you mean pod resource is not created in kcp? 
If so, what is the command you used to bring up the syncer? It should have had a --resources-to-sync=pods parameter.

**Comment by fgiloux** [comment] 2022-05-25 07:37
As discussed with Xin it is expected that Pods are not synced (at least for now). The issue is that th[e script ckcp/test.sh checks for them](https://github.com/openshift-pipelines/pipelines-service/blob/main/ckcp/test.sh#L35), which it should not do.

**Comment by fgiloux** [comment] 2022-05-25 07:38
My take on that is that we should be fixing the test script

**Comment by bnallapeta** [comment] 2022-05-25 07:52
Agreed. Also, earlier, we hardcoded kcp-generated-hash-namespace like [this](https://github.com/openshift-pipelines/pipelines-service/blob/main/ckcp/test.sh#L37). We need to dynamically get the namespace name. Its implemented [here](https://github.com/openshift-pipelines/pipelines-service/blob/main/kcp/test.sh#L37).
@XinRedhat Please take a look at this and do the same in ckcp/test.sh

**Comment by XinRedhat** [comment] 2022-05-25 08:49
@bnallapeta sure, thanks for sharing

**Comment by XinRedhat** [comment] 2022-05-25 11:07
fixed the issue in PR #79

**Comment by ramessesii2** [comment] 2022-06-02 10:30
Hey @XinRedhat, please close this issue as it has been resolved.

**Comment by ramessesii2** [comment] 2022-06-02 10:34
@XinRedhat Closing this issue as the PR #79  has been merged.

**Closed by ramessesii2** 2022-06-02 10:34 UTC
